// ============================================================
// Crowd Positioning Layer
// ------------------------------------------------------------
// Aggregated (anonymized) stance counts from EliteFlux's own
// users' logged calls — genuinely proprietary data nobody else
// has access to, since it's generated by this platform's own
// usage. Not exposed per-user, only as symbol-level totals.
// ============================================================
export interface CrowdSignal {
  symbol: string;
  accumulate: number;
  reduce: number;
  watch: number;
  avoid: number;
  net: number; // -1..1, positive = crowd leaning accumulate
  score: number; // 0..100
}

export interface CrowdIntel {
  perAsset: Record<string, CrowdSignal | undefined>;
  sampleSize: number;
  generatedAt: number;
}

const clamp = (n: number, min = 0, max = 100) => Math.max(min, Math.min(max, n));
const LOOKBACK_DAYS = 7;
const MIN_CALLS_PER_SYMBOL = 3; // below this, one loud user could swing the read

type Admin = { from: (t: string) => any };

/** Best-effort — a failed read just means no crowd signal this cycle. */
export async function loadCrowdIntel(admin: Admin): Promise<CrowdIntel> {
  const ts = Date.now();
  const empty: CrowdIntel = { perAsset: {}, sampleSize: 0, generatedAt: ts };
  try {
    const since = new Date(ts - LOOKBACK_DAYS * 86400_000).toISOString();
    const { data } = await admin
      .from("coach_calls")
      .select("symbol,stance")
      .gte("created_at", since)
      .limit(5000);
    const rows = (data ?? []) as { symbol: string; stance: string }[];
    if (!rows.length) return empty;

    const buckets = new Map<string, { accumulate: number; reduce: number; watch: number; avoid: number }>();
    for (const r of rows) {
      const b = buckets.get(r.symbol) ?? { accumulate: 0, reduce: 0, watch: 0, avoid: 0 };
      if (r.stance === "accumulate") b.accumulate++;
      else if (r.stance === "reduce") b.reduce++;
      else if (r.stance === "watch") b.watch++;
      else if (r.stance === "avoid") b.avoid++;
      buckets.set(r.symbol, b);
    }

    const perAsset: Record<string, CrowdSignal | undefined> = {};
    for (const [symbol, b] of buckets) {
      const total = b.accumulate + b.reduce + b.watch + b.avoid;
      if (total < MIN_CALLS_PER_SYMBOL) continue;
      const bullish = b.accumulate;
      const bearish = b.reduce + b.avoid;
      const net = (bullish - bearish) / total;
      perAsset[symbol] = {
        symbol,
        accumulate: b.accumulate,
        reduce: b.reduce,
        watch: b.watch,
        avoid: b.avoid,
        net: Math.round(net * 100) / 100,
        score: Math.round(clamp(50 + net * 50)),
      };
    }

    return { perAsset, sampleSize: rows.length, generatedAt: ts };
  } catch {
    return empty;
  }
}
