// Registers the background-job scheduler with Nitro's Cloudflare Workers
// runtime. Cloudflare Cron Triggers call the deployed Worker's own
// `scheduled` export — but on the "cloudflare-module" Nitro preset, that
// export is generated by Nitro itself (see
// node_modules/nitro/dist/presets/cloudflare/runtime/_module-handler.mjs),
// and it does nothing but fire a "cloudflare:scheduled" hook. A hand-written
// `scheduled` export elsewhere (e.g. on a custom server entry) is never
// actually wired to Cloudflare's dispatch — this hook is the real entry
// point. Without a listener here, every Cron Trigger fires, Cloudflare
// reports "Ok", and nothing downstream ever runs: no job body, no error, no
// log — completely silent.
import { definePlugin } from "nitro";
import { useNitroHooks } from "nitro/app";

export default definePlugin(() => {
  const hooks = useNitroHooks();
  hooks.hook("cloudflare:scheduled", async (event: { controller: { cron: string }; env: unknown }) => {
    // process.env (via the nodejs_compat flag) is populated for `fetch`
    // invocations but was observed empty here — every job body reads
    // credentials off process.env (e.g. client.server.ts's
    // createSupabaseAdminClient), so without this every scheduled run fails
    // before doing anything. `env` carries the exact same Worker bindings
    // Cloudflare passes to fetch(request, env, ctx); only string values are
    // real vars/secrets, everything else (KV/D1/Assets bindings) is skipped.
    if (event.env && typeof event.env === "object") {
      for (const [key, value] of Object.entries(event.env as Record<string, unknown>)) {
        if (typeof value === "string") process.env[key] = value;
      }
    }
    const { runScheduledTick } = await import("./scheduler.server");
    await runScheduledTick(event.controller.cron);
  });
});
