/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyElitefluxRouteImport } from './routes/why-eliteflux'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TrackRecordRouteImport } from './routes/track-record'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AutopilotRouteImport } from './routes/autopilot'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachIndexRouteImport } from './routes/coach/index'
import { Route as CoachThreadIdRouteImport } from './routes/coach/$threadId'
import { Route as AuthTelegramRouteImport } from './routes/auth/telegram'
import { Route as ApiCoachRouteImport } from './routes/api/coach'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ApiPublicSettlePaymentsRouteImport } from './routes/api/public/settle-payments'
import { Route as ApiPublicRetentionCleanupRouteImport } from './routes/api/public/retention-cleanup'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'
import { Route as ApiPublicMarketFeedRouteImport } from './routes/api/public/market-feed'
import { Route as ApiPublicExpireSubsRouteImport } from './routes/api/public/expire-subs'
import { Route as ApiPublicEvaluateAlertsRouteImport } from './routes/api/public/evaluate-alerts'
import { Route as ApiBrainWhaleRouteImport } from './routes/api/brain/whale'
import { Route as ApiBrainV3RouteImport } from './routes/api/brain/v3'
import { Route as ApiBrainSentimentRouteImport } from './routes/api/brain/sentiment'
import { Route as ApiBrainOnchainRouteImport } from './routes/api/brain/onchain'
import { Route as ApiBrainEliteFluxRouteImport } from './routes/api/brain/elite-flux'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const WhyElitefluxRoute = WhyElitefluxRouteImport.update({
  id: '/why-eliteflux',
  path: '/why-eliteflux',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRecordRoute = TrackRecordRouteImport.update({
  id: '/track-record',
  path: '/track-record',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AutopilotRoute = AutopilotRouteImport.update({
  id: '/autopilot',
  path: '/autopilot',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/coach/',
  path: '/coach/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachThreadIdRoute = CoachThreadIdRouteImport.update({
  id: '/coach/$threadId',
  path: '/coach/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTelegramRoute = AuthTelegramRouteImport.update({
  id: '/auth/telegram',
  path: '/auth/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoachRoute = ApiCoachRouteImport.update({
  id: '/api/coach',
  path: '/api/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSettlePaymentsRoute = ApiPublicSettlePaymentsRouteImport.update({
  id: '/api/public/settle-payments',
  path: '/api/public/settle-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRetentionCleanupRoute =
  ApiPublicRetentionCleanupRouteImport.update({
    id: '/api/public/retention-cleanup',
    path: '/api/public/retention-cleanup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMarketFeedRoute = ApiPublicMarketFeedRouteImport.update({
  id: '/api/public/market-feed',
  path: '/api/public/market-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExpireSubsRoute = ApiPublicExpireSubsRouteImport.update({
  id: '/api/public/expire-subs',
  path: '/api/public/expire-subs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEvaluateAlertsRoute = ApiPublicEvaluateAlertsRouteImport.update({
  id: '/api/public/evaluate-alerts',
  path: '/api/public/evaluate-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrainWhaleRoute = ApiBrainWhaleRouteImport.update({
  id: '/api/brain/whale',
  path: '/api/brain/whale',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrainV3Route = ApiBrainV3RouteImport.update({
  id: '/api/brain/v3',
  path: '/api/brain/v3',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrainSentimentRoute = ApiBrainSentimentRouteImport.update({
  id: '/api/brain/sentiment',
  path: '/api/brain/sentiment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrainOnchainRoute = ApiBrainOnchainRouteImport.update({
  id: '/api/brain/onchain',
  path: '/api/brain/onchain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrainEliteFluxRoute = ApiBrainEliteFluxRouteImport.update({
  id: '/api/brain/elite-flux',
  path: '/api/brain/elite-flux',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/autopilot': typeof AutopilotRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/owner': typeof OwnerRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/track-record': typeof TrackRecordRoute
  '/welcome': typeof WelcomeRoute
  '/why-eliteflux': typeof WhyElitefluxRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/coach': typeof ApiCoachRoute
  '/auth/telegram': typeof AuthTelegramRoute
  '/coach/$threadId': typeof CoachThreadIdRoute
  '/coach/': typeof CoachIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/brain/elite-flux': typeof ApiBrainEliteFluxRoute
  '/api/brain/onchain': typeof ApiBrainOnchainRoute
  '/api/brain/sentiment': typeof ApiBrainSentimentRoute
  '/api/brain/v3': typeof ApiBrainV3Route
  '/api/brain/whale': typeof ApiBrainWhaleRoute
  '/api/public/evaluate-alerts': typeof ApiPublicEvaluateAlertsRoute
  '/api/public/expire-subs': typeof ApiPublicExpireSubsRoute
  '/api/public/market-feed': typeof ApiPublicMarketFeedRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/retention-cleanup': typeof ApiPublicRetentionCleanupRoute
  '/api/public/settle-payments': typeof ApiPublicSettlePaymentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/autopilot': typeof AutopilotRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/owner': typeof OwnerRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/track-record': typeof TrackRecordRoute
  '/welcome': typeof WelcomeRoute
  '/why-eliteflux': typeof WhyElitefluxRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/coach': typeof ApiCoachRoute
  '/auth/telegram': typeof AuthTelegramRoute
  '/coach/$threadId': typeof CoachThreadIdRoute
  '/coach': typeof CoachIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/brain/elite-flux': typeof ApiBrainEliteFluxRoute
  '/api/brain/onchain': typeof ApiBrainOnchainRoute
  '/api/brain/sentiment': typeof ApiBrainSentimentRoute
  '/api/brain/v3': typeof ApiBrainV3Route
  '/api/brain/whale': typeof ApiBrainWhaleRoute
  '/api/public/evaluate-alerts': typeof ApiPublicEvaluateAlertsRoute
  '/api/public/expire-subs': typeof ApiPublicExpireSubsRoute
  '/api/public/market-feed': typeof ApiPublicMarketFeedRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/retention-cleanup': typeof ApiPublicRetentionCleanupRoute
  '/api/public/settle-payments': typeof ApiPublicSettlePaymentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/autopilot': typeof AutopilotRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/owner': typeof OwnerRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/track-record': typeof TrackRecordRoute
  '/welcome': typeof WelcomeRoute
  '/why-eliteflux': typeof WhyElitefluxRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/coach': typeof ApiCoachRoute
  '/auth/telegram': typeof AuthTelegramRoute
  '/coach/$threadId': typeof CoachThreadIdRoute
  '/coach/': typeof CoachIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/brain/elite-flux': typeof ApiBrainEliteFluxRoute
  '/api/brain/onchain': typeof ApiBrainOnchainRoute
  '/api/brain/sentiment': typeof ApiBrainSentimentRoute
  '/api/brain/v3': typeof ApiBrainV3Route
  '/api/brain/whale': typeof ApiBrainWhaleRoute
  '/api/public/evaluate-alerts': typeof ApiPublicEvaluateAlertsRoute
  '/api/public/expire-subs': typeof ApiPublicExpireSubsRoute
  '/api/public/market-feed': typeof ApiPublicMarketFeedRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/retention-cleanup': typeof ApiPublicRetentionCleanupRoute
  '/api/public/settle-payments': typeof ApiPublicSettlePaymentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/alerts'
    | '/autopilot'
    | '/login'
    | '/mcp'
    | '/owner'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/reset-password'
    | '/security'
    | '/terms'
    | '/track-record'
    | '/welcome'
    | '/why-eliteflux'
    | '/.well-known/oauth-protected-resource'
    | '/api/coach'
    | '/auth/telegram'
    | '/coach/$threadId'
    | '/coach/'
    | '/.lovable/oauth/consent'
    | '/api/brain/elite-flux'
    | '/api/brain/onchain'
    | '/api/brain/sentiment'
    | '/api/brain/v3'
    | '/api/brain/whale'
    | '/api/public/evaluate-alerts'
    | '/api/public/expire-subs'
    | '/api/public/market-feed'
    | '/api/public/paystack-webhook'
    | '/api/public/retention-cleanup'
    | '/api/public/settle-payments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/alerts'
    | '/autopilot'
    | '/login'
    | '/mcp'
    | '/owner'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/reset-password'
    | '/security'
    | '/terms'
    | '/track-record'
    | '/welcome'
    | '/why-eliteflux'
    | '/.well-known/oauth-protected-resource'
    | '/api/coach'
    | '/auth/telegram'
    | '/coach/$threadId'
    | '/coach'
    | '/.lovable/oauth/consent'
    | '/api/brain/elite-flux'
    | '/api/brain/onchain'
    | '/api/brain/sentiment'
    | '/api/brain/v3'
    | '/api/brain/whale'
    | '/api/public/evaluate-alerts'
    | '/api/public/expire-subs'
    | '/api/public/market-feed'
    | '/api/public/paystack-webhook'
    | '/api/public/retention-cleanup'
    | '/api/public/settle-payments'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/alerts'
    | '/autopilot'
    | '/login'
    | '/mcp'
    | '/owner'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/reset-password'
    | '/security'
    | '/terms'
    | '/track-record'
    | '/welcome'
    | '/why-eliteflux'
    | '/.well-known/oauth-protected-resource'
    | '/api/coach'
    | '/auth/telegram'
    | '/coach/$threadId'
    | '/coach/'
    | '/.lovable/oauth/consent'
    | '/api/brain/elite-flux'
    | '/api/brain/onchain'
    | '/api/brain/sentiment'
    | '/api/brain/v3'
    | '/api/brain/whale'
    | '/api/public/evaluate-alerts'
    | '/api/public/expire-subs'
    | '/api/public/market-feed'
    | '/api/public/paystack-webhook'
    | '/api/public/retention-cleanup'
    | '/api/public/settle-payments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AlertsRoute: typeof AlertsRoute
  AutopilotRoute: typeof AutopilotRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  OwnerRoute: typeof OwnerRoute
  PortfolioRoute: typeof PortfolioRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityRoute: typeof SecurityRoute
  TermsRoute: typeof TermsRoute
  TrackRecordRoute: typeof TrackRecordRoute
  WelcomeRoute: typeof WelcomeRoute
  WhyElitefluxRoute: typeof WhyElitefluxRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiCoachRoute: typeof ApiCoachRoute
  AuthTelegramRoute: typeof AuthTelegramRoute
  CoachThreadIdRoute: typeof CoachThreadIdRoute
  CoachIndexRoute: typeof CoachIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiBrainEliteFluxRoute: typeof ApiBrainEliteFluxRoute
  ApiBrainOnchainRoute: typeof ApiBrainOnchainRoute
  ApiBrainSentimentRoute: typeof ApiBrainSentimentRoute
  ApiBrainV3Route: typeof ApiBrainV3Route
  ApiBrainWhaleRoute: typeof ApiBrainWhaleRoute
  ApiPublicEvaluateAlertsRoute: typeof ApiPublicEvaluateAlertsRoute
  ApiPublicExpireSubsRoute: typeof ApiPublicExpireSubsRoute
  ApiPublicMarketFeedRoute: typeof ApiPublicMarketFeedRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
  ApiPublicRetentionCleanupRoute: typeof ApiPublicRetentionCleanupRoute
  ApiPublicSettlePaymentsRoute: typeof ApiPublicSettlePaymentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-eliteflux': {
      id: '/why-eliteflux'
      path: '/why-eliteflux'
      fullPath: '/why-eliteflux'
      preLoaderRoute: typeof WhyElitefluxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-record': {
      id: '/track-record'
      path: '/track-record'
      fullPath: '/track-record'
      preLoaderRoute: typeof TrackRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autopilot': {
      id: '/autopilot'
      path: '/autopilot'
      fullPath: '/autopilot'
      preLoaderRoute: typeof AutopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/': {
      id: '/coach/'
      path: '/coach'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/$threadId': {
      id: '/coach/$threadId'
      path: '/coach/$threadId'
      fullPath: '/coach/$threadId'
      preLoaderRoute: typeof CoachThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/telegram': {
      id: '/auth/telegram'
      path: '/auth/telegram'
      fullPath: '/auth/telegram'
      preLoaderRoute: typeof AuthTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coach': {
      id: '/api/coach'
      path: '/api/coach'
      fullPath: '/api/coach'
      preLoaderRoute: typeof ApiCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/settle-payments': {
      id: '/api/public/settle-payments'
      path: '/api/public/settle-payments'
      fullPath: '/api/public/settle-payments'
      preLoaderRoute: typeof ApiPublicSettlePaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/retention-cleanup': {
      id: '/api/public/retention-cleanup'
      path: '/api/public/retention-cleanup'
      fullPath: '/api/public/retention-cleanup'
      preLoaderRoute: typeof ApiPublicRetentionCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/market-feed': {
      id: '/api/public/market-feed'
      path: '/api/public/market-feed'
      fullPath: '/api/public/market-feed'
      preLoaderRoute: typeof ApiPublicMarketFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/expire-subs': {
      id: '/api/public/expire-subs'
      path: '/api/public/expire-subs'
      fullPath: '/api/public/expire-subs'
      preLoaderRoute: typeof ApiPublicExpireSubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/evaluate-alerts': {
      id: '/api/public/evaluate-alerts'
      path: '/api/public/evaluate-alerts'
      fullPath: '/api/public/evaluate-alerts'
      preLoaderRoute: typeof ApiPublicEvaluateAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brain/whale': {
      id: '/api/brain/whale'
      path: '/api/brain/whale'
      fullPath: '/api/brain/whale'
      preLoaderRoute: typeof ApiBrainWhaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brain/v3': {
      id: '/api/brain/v3'
      path: '/api/brain/v3'
      fullPath: '/api/brain/v3'
      preLoaderRoute: typeof ApiBrainV3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brain/sentiment': {
      id: '/api/brain/sentiment'
      path: '/api/brain/sentiment'
      fullPath: '/api/brain/sentiment'
      preLoaderRoute: typeof ApiBrainSentimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brain/onchain': {
      id: '/api/brain/onchain'
      path: '/api/brain/onchain'
      fullPath: '/api/brain/onchain'
      preLoaderRoute: typeof ApiBrainOnchainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brain/elite-flux': {
      id: '/api/brain/elite-flux'
      path: '/api/brain/elite-flux'
      fullPath: '/api/brain/elite-flux'
      preLoaderRoute: typeof ApiBrainEliteFluxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AlertsRoute: AlertsRoute,
  AutopilotRoute: AutopilotRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  OwnerRoute: OwnerRoute,
  PortfolioRoute: PortfolioRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityRoute: SecurityRoute,
  TermsRoute: TermsRoute,
  TrackRecordRoute: TrackRecordRoute,
  WelcomeRoute: WelcomeRoute,
  WhyElitefluxRoute: WhyElitefluxRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiCoachRoute: ApiCoachRoute,
  AuthTelegramRoute: AuthTelegramRoute,
  CoachThreadIdRoute: CoachThreadIdRoute,
  CoachIndexRoute: CoachIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiBrainEliteFluxRoute: ApiBrainEliteFluxRoute,
  ApiBrainOnchainRoute: ApiBrainOnchainRoute,
  ApiBrainSentimentRoute: ApiBrainSentimentRoute,
  ApiBrainV3Route: ApiBrainV3Route,
  ApiBrainWhaleRoute: ApiBrainWhaleRoute,
  ApiPublicEvaluateAlertsRoute: ApiPublicEvaluateAlertsRoute,
  ApiPublicExpireSubsRoute: ApiPublicExpireSubsRoute,
  ApiPublicMarketFeedRoute: ApiPublicMarketFeedRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
  ApiPublicRetentionCleanupRoute: ApiPublicRetentionCleanupRoute,
  ApiPublicSettlePaymentsRoute: ApiPublicSettlePaymentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
